version: "2"
services:
  web:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app:rw
      - /app/node_modules #ignore local node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    command: npm run start:dev
